/* Generated by Yosys 0.62 (git sha1 7326bb7d6641500ecb285c291a54a662cb1e76cf, clang++ 17.0.0 -fPIC -O3) */

(* src = "gcd.v:109.1-320.10" *)
module GcdUnitCtrlRTL_0x4d0fc71ead8d3d9e(a_mux_sel, a_reg_en, b_mux_sel, b_reg_en, clk, is_a_lt_b, is_b_zero, req_rdy, req_val, reset, resp_rdy, resp_val);
  (* src = "gcd.v:111.24-111.33" *)
  output [1:0] a_mux_sel;
  wire [1:0] a_mux_sel;
  (* src = "gcd.v:112.24-112.32" *)
  output [0:0] a_reg_en;
  wire [0:0] a_reg_en;
  (* src = "gcd.v:113.24-113.33" *)
  output [0:0] b_mux_sel;
  wire [0:0] b_mux_sel;
  (* src = "gcd.v:114.24-114.32" *)
  output [0:0] b_reg_en;
  wire [0:0] b_reg_en;
  (* src = "gcd.v:115.24-115.27" *)
  input [0:0] clk;
  wire [0:0] clk;
  (* src = "gcd.v:116.24-116.33" *)
  input [0:0] is_a_lt_b;
  wire [0:0] is_a_lt_b;
  (* src = "gcd.v:117.24-117.33" *)
  input [0:0] is_b_zero;
  wire [0:0] is_b_zero;
  (* src = "gcd.v:118.24-118.31" *)
  output [0:0] req_rdy;
  wire [0:0] req_rdy;
  (* src = "gcd.v:119.24-119.31" *)
  input [0:0] req_val;
  wire [0:0] req_val;
  (* src = "gcd.v:120.24-120.29" *)
  input [0:0] reset;
  wire [0:0] reset;
  (* src = "gcd.v:121.24-121.32" *)
  input [0:0] resp_rdy;
  wire [0:0] resp_rdy;
  (* src = "gcd.v:122.24-122.32" *)
  output [0:0] resp_val;
  wire [0:0] resp_val;
  (* src = "gcd.v:192.3-223.6" *)
  wire [1:0] _000_;
  (* src = "gcd.v:277.3-317.6" *)
  wire [1:0] _001_;
  (* src = "gcd.v:277.3-317.6" *)
  wire _002_;
  (* src = "gcd.v:277.3-317.6" *)
  wire _003_;
  (* src = "gcd.v:192.3-223.6" *)
  wire [1:0] _004_;
  (* src = "gcd.v:277.3-317.6" *)
  wire _005_;
  (* src = "gcd.v:192.3-223.6" *)
  wire [1:0] _006_;
  (* src = "gcd.v:277.3-317.6" *)
  wire _007_;
  (* src = "gcd.v:192.3-223.6" *)
  wire [1:0] _008_;
  (* src = "gcd.v:192.3-223.6" *)
  wire [1:0] _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  (* src = "gcd.v:204.10-204.37" *)
  wire _100_;
  (* src = "gcd.v:213.10-213.37" *)
  wire _101_;
  (* src = "gcd.v:196.12-196.28" *)
  wire _102_;
  (* src = "gcd.v:205.12-205.33" *)
  wire _103_;
  (* src = "gcd.v:214.12-214.30" *)
  wire _104_;
  (* src = "gcd.v:205.12-205.22" *)
  wire _105_;
  (* src = "gcd.v:293.21-293.58" *)
  (* unused_bits = "2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _106_;
  (* src = "gcd.v:126.19-126.32" *)
  wire [1:0] curr_state__0;
  (* src = "gcd.v:127.19-127.35" *)
  wire [1:0] current_state__1;
  (* src = "gcd.v:130.19-130.32" *)
  wire [1:0] next_state__0;
  (* src = "gcd.v:147.19-147.28" *)
  wire [0:0] \state$clk ;
  (* src = "gcd.v:131.19-131.28" *)
  wire [1:0] \state$in_ ;
  (* src = "gcd.v:148.19-148.28" *)
  wire [1:0] \state$out ;
  (* src = "gcd.v:146.19-146.30" *)
  wire [0:0] \state$reset ;
  gf180mcu_fd_sc_mcu7t5v0__tieh_1 _107_ (
    .Y(_010_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tieh_1 _108_ (
    .Y(_011_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tieh_1 _109_ (
    .Y(_012_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tieh_1 _110_ (
    .Y(_013_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tieh_1 _111_ (
    .Y(_014_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tieh_1 _112_ (
    .Y(_015_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tieh_1 _113_ (
    .Y(_016_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tieh_1 _114_ (
    .Y(_017_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tieh_1 _115_ (
    .Y(_018_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tieh_1 _116_ (
    .Y(_019_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tieh_1 _117_ (
    .Y(_020_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel_1 _118_ (
    .Y(_021_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel_1 _119_ (
    .Y(_022_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel_1 _120_ (
    .Y(_023_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel_1 _121_ (
    .Y(_024_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel_1 _122_ (
    .Y(_025_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel_1 _123_ (
    .Y(_026_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel_1 _124_ (
    .Y(_027_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel_1 _125_ (
    .Y(_028_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel_1 _126_ (
    .Y(_029_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel_1 _127_ (
    .Y(_030_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel_1 _128_ (
    .Y(_031_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel_1 _129_ (
    .Y(_032_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel_1 _130_ (
    .Y(_033_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel_1 _131_ (
    .Y(_034_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel_1 _132_ (
    .Y(_035_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel_1 _133_ (
    .Y(_036_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel_1 _134_ (
    .Y(_037_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel_1 _135_ (
    .Y(_038_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel_1 _136_ (
    .Y(_039_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel_1 _137_ (
    .Y(_040_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel_1 _138_ (
    .Y(_041_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel_1 _139_ (
    .Y(_042_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel_1 _140_ (
    .Y(_043_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel_1 _141_ (
    .Y(_044_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel_1 _142_ (
    .Y(_045_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel_1 _143_ (
    .Y(_046_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel_1 _144_ (
    .Y(_047_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel_1 _145_ (
    .Y(_048_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel_1 _146_ (
    .Y(_049_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel_1 _147_ (
    .Y(_050_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel_1 _148_ (
    .Y(_051_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel_1 _149_ (
    .Y(_052_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel_1 _150_ (
    .Y(_053_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel_1 _151_ (
    .Y(_054_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel_1 _152_ (
    .Y(_055_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel_1 _153_ (
    .Y(_056_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel_1 _154_ (
    .Y(_057_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel_1 _155_ (
    .Y(_058_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel_1 _156_ (
    .Y(_059_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel_1 _157_ (
    .Y(_060_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel_1 _158_ (
    .Y(_061_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel_1 _159_ (
    .Y(_062_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel_1 _160_ (
    .Y(_063_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel_1 _161_ (
    .Y(_064_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel_1 _162_ (
    .Y(_065_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel_1 _163_ (
    .Y(_066_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel_1 _164_ (
    .Y(_067_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel_1 _165_ (
    .Y(_068_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel_1 _166_ (
    .Y(_069_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel_1 _167_ (
    .Y(_070_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel_1 _168_ (
    .Y(_071_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel_1 _169_ (
    .Y(_072_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel_1 _170_ (
    .Y(_073_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel_1 _171_ (
    .Y(_074_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel_1 _172_ (
    .Y(_075_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel_1 _173_ (
    .Y(_076_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel_1 _174_ (
    .Y(_077_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel_1 _175_ (
    .Y(_078_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel_1 _176_ (
    .Y(_079_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel_1 _177_ (
    .Y(_080_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel_1 _178_ (
    .Y(_081_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel_1 _179_ (
    .Y(_082_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel_1 _180_ (
    .Y(_083_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel_1 _181_ (
    .Y(_084_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel_1 _182_ (
    .Y(_085_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel_1 _183_ (
    .Y(_086_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel_1 _184_ (
    .Y(_087_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel_1 _185_ (
    .Y(_088_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel_1 _186_ (
    .Y(_089_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel_1 _187_ (
    .Y(_090_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel_1 _188_ (
    .Y(_091_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel_1 _189_ (
    .Y(_092_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel_1 _190_ (
    .Y(_093_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel_1 _191_ (
    .Y(_094_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel_1 _192_ (
    .Y(_095_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel_1 _193_ (
    .Y(_096_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel_1 _194_ (
    .Y(_097_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel_1 _195_ (
    .Y(_098_)
  );
  assign _099_ = ! (* src = "gcd.v:279.10-279.40" *) \state$out ;
  assign _100_ = \state$out  == (* src = "gcd.v:288.12-288.42" *) { _021_, _010_ };
  assign _101_ = \state$out  == (* src = "gcd.v:299.14-299.44" *) { _011_, _022_ };
  assign _102_ = req_val && (* src = "gcd.v:196.12-196.28" *) req_rdy;
  assign _103_ = _105_ && (* src = "gcd.v:205.12-205.33" *) is_b_zero;
  assign _104_ = resp_val && (* src = "gcd.v:214.12-214.30" *) resp_rdy;
  assign _105_ = ! (* src = "gcd.v:205.12-205.22" *) is_a_lt_b;
  assign _003_ = _100_ ? (* full_case = 32'd1 *) (* src = "gcd.v:288.11-288.43|gcd.v:288.7-315.10" *) is_a_lt_b : _023_;
  assign _002_ = _100_ ? (* full_case = 32'd1 *) (* src = "gcd.v:288.11-288.43|gcd.v:288.7-315.10" *) _012_ : _024_;
  assign _001_ = _100_ ? (* full_case = 32'd1 *) (* src = "gcd.v:288.11-288.43|gcd.v:288.7-315.10" *) _106_[1:0] : { _026_, _025_ };
  assign _005_ = _100_ ? (* full_case = 32'd1 *) (* src = "gcd.v:288.11-288.43|gcd.v:288.7-315.10" *) _027_ : _007_;
  assign b_reg_en = _099_ ? (* full_case = 32'd1 *) (* src = "gcd.v:279.9-279.41|gcd.v:279.5-316.8" *) _013_ : _003_;
  assign a_reg_en = _099_ ? (* full_case = 32'd1 *) (* src = "gcd.v:279.9-279.41|gcd.v:279.5-316.8" *) _014_ : _002_;
  assign a_mux_sel = _099_ ? (* full_case = 32'd1 *) (* src = "gcd.v:279.9-279.41|gcd.v:279.5-316.8" *) { _029_, _028_ } : _001_;
  assign resp_val = _099_ ? (* full_case = 32'd1 *) (* src = "gcd.v:279.9-279.41|gcd.v:279.5-316.8" *) _030_ : _005_;
  assign req_rdy = _099_ ? (* full_case = 32'd1 *) (* src = "gcd.v:279.9-279.41|gcd.v:279.5-316.8" *) _015_ : _031_;
  assign _009_ = _104_ ? (* full_case = 32'd1 *) (* src = "gcd.v:214.11-214.31|gcd.v:214.7-218.10" *) { _033_, _032_ } : _006_;
  assign \state$in_  = _101_ ? (* full_case = 32'd1 *) (* src = "gcd.v:213.9-213.38|gcd.v:213.5-221.8" *) _009_ : _006_;
  assign _008_ = _103_ ? (* full_case = 32'd1 *) (* src = "gcd.v:205.11-205.34|gcd.v:205.7-209.10" *) { _016_, _034_ } : _000_;
  assign _006_ = _100_ ? (* full_case = 32'd1 *) (* src = "gcd.v:204.9-204.38|gcd.v:204.5-212.8" *) _008_ : _000_;
  assign _004_ = _102_ ? (* full_case = 32'd1 *) (* src = "gcd.v:196.11-196.29|gcd.v:196.7-200.10" *) { _035_, _017_ } : \state$out ;
  assign _000_ = _099_ ? (* full_case = 32'd1 *) (* src = "gcd.v:195.9-195.38|gcd.v:195.5-203.8" *) _004_ : \state$out ;
  assign _007_ = _101_ ? (* full_case = 32'd1 *) (* src = "gcd.v:299.13-299.45|gcd.v:299.9-314.12" *) _018_ : _036_;
  assign _106_ = is_a_lt_b ? (* src = "gcd.v:293.21-293.58" *) { _098_, _097_, _096_, _095_, _094_, _093_, _092_, _091_, _090_, _089_, _088_, _087_, _086_, _085_, _084_, _083_, _082_, _081_, _080_, _079_, _078_, _077_, _076_, _075_, _074_, _073_, _072_, _071_, _070_, _069_, _020_, _068_ } : { _067_, _066_, _065_, _064_, _063_, _062_, _061_, _060_, _059_, _058_, _057_, _056_, _055_, _054_, _053_, _052_, _051_, _050_, _049_, _048_, _047_, _046_, _045_, _044_, _043_, _042_, _041_, _040_, _039_, _038_, _037_, _019_ };
  (* module_not_derived = 32'd1 *)
  (* src = "gcd.v:150.28-156.4" *)
  RegRst_0x9f365fdf6c8998a state (
    .clk(clk),
    .in_(\state$in_ ),
    .out(\state$out ),
    .reset(reset)
  );
  assign b_mux_sel = req_rdy;
  assign curr_state__0 = \state$out ;
  assign current_state__1 = \state$out ;
  assign next_state__0 = \state$in_ ;
  assign \state$clk  = clk;
  assign \state$reset  = reset;
endmodule

(* src = "gcd.v:369.1-544.10" *)
module GcdUnitDpathRTL_0x4d0fc71ead8d3d9e(a_mux_sel, a_reg_en, b_mux_sel, b_reg_en, clk, is_a_lt_b, is_b_zero, req_msg_a, req_msg_b, reset, resp_msg);
  (* src = "gcd.v:371.24-371.33" *)
  input [1:0] a_mux_sel;
  wire [1:0] a_mux_sel;
  (* src = "gcd.v:372.24-372.32" *)
  input [0:0] a_reg_en;
  wire [0:0] a_reg_en;
  (* src = "gcd.v:373.24-373.33" *)
  input [0:0] b_mux_sel;
  wire [0:0] b_mux_sel;
  (* src = "gcd.v:374.24-374.32" *)
  input [0:0] b_reg_en;
  wire [0:0] b_reg_en;
  (* src = "gcd.v:375.24-375.27" *)
  input [0:0] clk;
  wire [0:0] clk;
  (* src = "gcd.v:376.24-376.33" *)
  output [0:0] is_a_lt_b;
  wire [0:0] is_a_lt_b;
  (* src = "gcd.v:377.24-377.33" *)
  output [0:0] is_b_zero;
  wire [0:0] is_b_zero;
  (* src = "gcd.v:378.24-378.33" *)
  input [15:0] req_msg_a;
  wire [15:0] req_msg_a;
  (* src = "gcd.v:379.24-379.33" *)
  input [15:0] req_msg_b;
  wire [15:0] req_msg_b;
  (* src = "gcd.v:380.24-380.29" *)
  input [0:0] reset;
  wire [0:0] reset;
  (* src = "gcd.v:381.24-381.32" *)
  output [15:0] resp_msg;
  wire [15:0] resp_msg;
  (* src = "gcd.v:407.19-407.29" *)
  wire [0:0] \a_lt_b$clk ;
  (* src = "gcd.v:408.19-408.29" *)
  wire [15:0] \a_lt_b$in0 ;
  (* src = "gcd.v:409.19-409.29" *)
  wire [15:0] \a_lt_b$in1 ;
  (* src = "gcd.v:410.19-410.29" *)
  wire [0:0] \a_lt_b$out ;
  (* src = "gcd.v:406.19-406.31" *)
  wire [0:0] \a_lt_b$reset ;
  (* src = "gcd.v:440.19-440.28" *)
  wire [0:0] \a_mux$clk ;
  (* src = "gcd.v:437.19-437.32" *)
  wire [15:0] \a_mux$in_$000 ;
  (* src = "gcd.v:438.19-438.32" *)
  wire [15:0] \a_mux$in_$001 ;
  (* src = "gcd.v:439.19-439.32" *)
  wire [15:0] \a_mux$in_$002 ;
  (* src = "gcd.v:442.19-442.28" *)
  wire [15:0] \a_mux$out ;
  (* src = "gcd.v:436.19-436.30" *)
  wire [0:0] \a_mux$reset ;
  (* src = "gcd.v:441.19-441.28" *)
  wire [1:0] \a_mux$sel ;
  (* src = "gcd.v:392.19-392.28" *)
  wire [0:0] \a_reg$clk ;
  (* src = "gcd.v:393.19-393.27" *)
  wire [0:0] \a_reg$en ;
  (* src = "gcd.v:391.19-391.28" *)
  wire [15:0] \a_reg$in_ ;
  (* src = "gcd.v:394.19-394.28" *)
  wire [15:0] \a_reg$out ;
  (* src = "gcd.v:390.19-390.30" *)
  wire [0:0] \a_reg$reset ;
  (* src = "gcd.v:459.19-459.28" *)
  wire [0:0] \b_mux$clk ;
  (* src = "gcd.v:457.19-457.32" *)
  wire [15:0] \b_mux$in_$000 ;
  (* src = "gcd.v:458.19-458.32" *)
  wire [15:0] \b_mux$in_$001 ;
  (* src = "gcd.v:461.19-461.28" *)
  wire [15:0] \b_mux$out ;
  (* src = "gcd.v:456.19-456.30" *)
  wire [0:0] \b_mux$reset ;
  (* src = "gcd.v:460.19-460.28" *)
  wire [0:0] \b_mux$sel ;
  (* src = "gcd.v:492.19-492.28" *)
  wire [0:0] \b_reg$clk ;
  (* src = "gcd.v:493.19-493.27" *)
  wire [0:0] \b_reg$en ;
  (* src = "gcd.v:491.19-491.28" *)
  wire [15:0] \b_reg$in_ ;
  (* src = "gcd.v:494.19-494.28" *)
  wire [15:0] \b_reg$out ;
  (* src = "gcd.v:490.19-490.30" *)
  wire [0:0] \b_reg$reset ;
  (* src = "gcd.v:386.19-386.28" *)
  wire [15:0] b_reg_out;
  (* src = "gcd.v:424.19-424.29" *)
  wire [0:0] \b_zero$clk ;
  (* src = "gcd.v:423.19-423.29" *)
  wire [15:0] \b_zero$in_ ;
  (* src = "gcd.v:425.19-425.29" *)
  wire [0:0] \b_zero$out ;
  (* src = "gcd.v:422.19-422.31" *)
  wire [0:0] \b_zero$reset ;
  (* src = "gcd.v:475.19-475.26" *)
  wire [0:0] \sub$clk ;
  (* src = "gcd.v:476.19-476.26" *)
  wire [15:0] \sub$in0 ;
  (* src = "gcd.v:477.19-477.26" *)
  wire [15:0] \sub$in1 ;
  (* src = "gcd.v:478.19-478.26" *)
  wire [15:0] \sub$out ;
  (* src = "gcd.v:474.19-474.28" *)
  wire [0:0] \sub$reset ;
  (* src = "gcd.v:385.19-385.26" *)
  wire [15:0] sub_out;
  (* module_not_derived = 32'd1 *)
  (* src = "gcd.v:412.35-419.4" *)
  LtComparator_0x422b1f52edd46a85 a_lt_b (
    .clk(clk),
    .in0(\a_lt_b$in0 ),
    .in1(\a_lt_b$in1 ),
    .out(\a_lt_b$out ),
    .reset(reset)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "gcd.v:444.26-453.4" *)
  Mux_0x683fa1a418b072c9 a_mux (
    .clk(clk),
    .\in_$000 (req_msg_a),
    .\in_$001 (\a_mux$in_$001 ),
    .\in_$002 (\a_lt_b$in1 ),
    .out(\a_mux$out ),
    .reset(reset),
    .sel(a_mux_sel)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "gcd.v:396.28-403.4" *)
  RegEn_0x68db79c4ec1d6e5b a_reg (
    .clk(clk),
    .en(a_reg_en),
    .in_(\a_mux$out ),
    .out(\a_lt_b$in0 ),
    .reset(reset)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "gcd.v:463.25-471.4" *)
  Mux_0xdd6473406d1a99a b_mux (
    .clk(clk),
    .\in_$000 (\a_lt_b$in0 ),
    .\in_$001 (req_msg_b),
    .out(\b_mux$out ),
    .reset(reset),
    .sel(b_mux_sel)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "gcd.v:496.28-503.4" *)
  RegEn_0x68db79c4ec1d6e5b b_reg (
    .clk(clk),
    .en(b_reg_en),
    .in_(\b_mux$out ),
    .out(\a_lt_b$in1 ),
    .reset(reset)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "gcd.v:427.37-433.4" *)
  ZeroComparator_0x422b1f52edd46a85 b_zero (
    .clk(clk),
    .in_(\a_lt_b$in1 ),
    .out(\b_zero$out ),
    .reset(reset)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "gcd.v:480.33-487.4" *)
  Subtractor_0x422b1f52edd46a85 sub (
    .clk(clk),
    .in0(\a_lt_b$in0 ),
    .in1(\a_lt_b$in1 ),
    .out(\a_mux$in_$001 ),
    .reset(reset)
  );
  assign \a_lt_b$clk  = clk;
  assign \a_lt_b$reset  = reset;
  assign \a_mux$clk  = clk;
  assign \a_mux$in_$000  = req_msg_a;
  assign \a_mux$in_$002  = \a_lt_b$in1 ;
  assign \a_mux$reset  = reset;
  assign \a_mux$sel  = a_mux_sel;
  assign \a_reg$clk  = clk;
  assign \a_reg$en  = a_reg_en;
  assign \a_reg$in_  = \a_mux$out ;
  assign \a_reg$out  = \a_lt_b$in0 ;
  assign \a_reg$reset  = reset;
  assign \b_mux$clk  = clk;
  assign \b_mux$in_$000  = \a_lt_b$in0 ;
  assign \b_mux$in_$001  = req_msg_b;
  assign \b_mux$reset  = reset;
  assign \b_mux$sel  = b_mux_sel;
  assign \b_reg$clk  = clk;
  assign \b_reg$en  = b_reg_en;
  assign \b_reg$in_  = \b_mux$out ;
  assign \b_reg$out  = \a_lt_b$in1 ;
  assign \b_reg$reset  = reset;
  assign b_reg_out = \a_lt_b$in1 ;
  assign \b_zero$clk  = clk;
  assign \b_zero$in_  = \a_lt_b$in1 ;
  assign \b_zero$reset  = reset;
  assign is_a_lt_b = \a_lt_b$out ;
  assign is_b_zero = \b_zero$out ;
  assign resp_msg = \a_mux$in_$001 ;
  assign \sub$clk  = clk;
  assign \sub$in0  = \a_lt_b$in0 ;
  assign \sub$in1  = \a_lt_b$in1 ;
  assign \sub$out  = \a_mux$in_$001 ;
  assign \sub$reset  = reset;
  assign sub_out = \a_mux$in_$001 ;
endmodule

(* src = "gcd.v:588.1-611.10" *)
module LtComparator_0x422b1f52edd46a85(clk, in0, in1, out, reset);
  (* src = "gcd.v:590.24-590.27" *)
  input [0:0] clk;
  wire [0:0] clk;
  (* src = "gcd.v:591.24-591.27" *)
  input [15:0] in0;
  wire [15:0] in0;
  (* src = "gcd.v:592.24-592.27" *)
  input [15:0] in1;
  wire [15:0] in1;
  (* src = "gcd.v:593.24-593.27" *)
  output [0:0] out;
  wire [0:0] out;
  (* src = "gcd.v:594.24-594.29" *)
  input [0:0] reset;
  wire [0:0] reset;
  assign out = in0 < (* src = "gcd.v:607.12-607.21" *) in1;
endmodule

(* src = "gcd.v:650.1-684.10" *)
module Mux_0x683fa1a418b072c9(clk, \in_$000 , \in_$001 , \in_$002 , out, reset, sel);
  (* src = "gcd.v:652.24-652.27" *)
  input [0:0] clk;
  wire [0:0] clk;
  (* src = "gcd.v:653.24-653.31" *)
  input [15:0] \in_$000 ;
  wire [15:0] \in_$000 ;
  (* src = "gcd.v:654.24-654.31" *)
  input [15:0] \in_$001 ;
  wire [15:0] \in_$001 ;
  (* src = "gcd.v:655.24-655.31" *)
  input [15:0] \in_$002 ;
  wire [15:0] \in_$002 ;
  (* src = "gcd.v:656.24-656.27" *)
  output [15:0] out;
  wire [15:0] out;
  (* src = "gcd.v:657.24-657.29" *)
  input [0:0] reset;
  wire [0:0] reset;
  (* src = "gcd.v:658.24-658.27" *)
  input [1:0] sel;
  wire [1:0] sel;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  (* src = "gcd.v:666.19-666.22" *)
  wire [15:0] \in_[0] ;
  (* src = "gcd.v:666.19-666.22" *)
  wire [15:0] \in_[1] ;
  (* src = "gcd.v:666.19-666.22" *)
  wire [15:0] \in_[2] ;
  gf180mcu_fd_sc_mcu7t5v0__tieh_1 _07_ (
    .Y(_00_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tieh_1 _08_ (
    .Y(_01_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel_1 _09_ (
    .Y(_02_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel_1 _10_ (
    .Y(_03_)
  );
  function [15:0] _11_;
    input [15:0] a;
    input [47:0] b;
    input [2:0] s;
    (* full_case = 32'd1 *)
    (* src = "gcd.v:680.11-680.14" *)
    (* parallel_case *)
    casez (s)
      3'b??1:
        _11_ = b[15:0];
      3'b?1?:
        _11_ = b[31:16];
      3'b1??:
        _11_ = b[47:32];
      default:
        _11_ = a;
    endcase
  endfunction
  assign out = _11_(16'hxxxx, { \in_$000 , \in_$001 , \in_$002  }, { _06_, _05_, _04_ });
  assign _04_ = sel == (* full_case = 32'd1 *) (* src = "gcd.v:680.11-680.14" *) { _00_, _02_ };
  assign _05_ = sel == (* full_case = 32'd1 *) (* src = "gcd.v:680.11-680.14" *) { _03_, _01_ };
  assign _06_ = ! (* full_case = 32'd1 *) (* src = "gcd.v:680.11-680.14" *) sel;
  assign \in_[0]  = \in_$000 ;
  assign \in_[1]  = \in_$001 ;
  assign \in_[2]  = \in_$002 ;
endmodule

(* src = "gcd.v:693.1-725.10" *)
module Mux_0xdd6473406d1a99a(clk, \in_$000 , \in_$001 , out, reset, sel);
  (* src = "gcd.v:695.24-695.27" *)
  input [0:0] clk;
  wire [0:0] clk;
  (* src = "gcd.v:696.24-696.31" *)
  input [15:0] \in_$000 ;
  wire [15:0] \in_$000 ;
  (* src = "gcd.v:697.24-697.31" *)
  input [15:0] \in_$001 ;
  wire [15:0] \in_$001 ;
  (* src = "gcd.v:698.24-698.27" *)
  output [15:0] out;
  wire [15:0] out;
  (* src = "gcd.v:699.24-699.29" *)
  input [0:0] reset;
  wire [0:0] reset;
  (* src = "gcd.v:700.24-700.27" *)
  input [0:0] sel;
  wire [0:0] sel;
  wire _0_;
  (* src = "gcd.v:708.19-708.22" *)
  wire [15:0] \in_[0] ;
  (* src = "gcd.v:708.19-708.22" *)
  wire [15:0] \in_[1] ;
  function [15:0] _1_;
    input [15:0] a;
    input [31:0] b;
    input [1:0] s;
    (* full_case = 32'd1 *)
    (* src = "gcd.v:721.11-721.14" *)
    (* parallel_case *)
    casez (s)
      2'b?1:
        _1_ = b[15:0];
      2'b1?:
        _1_ = b[31:16];
      default:
        _1_ = a;
    endcase
  endfunction
  assign out = _1_(16'hxxxx, { \in_$000 , \in_$001  }, { _0_, sel });
  assign _0_ = ~ (* full_case = 32'd1 *) (* src = "gcd.v:721.11-721.14" *) sel;
  assign \in_[0]  = \in_$000 ;
  assign \in_[1]  = \in_$001 ;
endmodule

(* src = "gcd.v:552.1-580.10" *)
module RegEn_0x68db79c4ec1d6e5b(clk, en, in_, out, reset);
  (* src = "gcd.v:554.24-554.27" *)
  input [0:0] clk;
  wire [0:0] clk;
  (* src = "gcd.v:555.24-555.26" *)
  input [0:0] en;
  wire [0:0] en;
  (* src = "gcd.v:556.24-556.27" *)
  input [15:0] in_;
  wire [15:0] in_;
  (* src = "gcd.v:557.24-557.27" *)
  output [15:0] out;
  reg [15:0] out;
  (* src = "gcd.v:558.24-558.29" *)
  input [0:0] reset;
  wire [0:0] reset;
  (* src = "gcd.v:571.3-577.6" *)
  always @(posedge clk)
    if (en) out <= in_;
endmodule

(* src = "gcd.v:329.1-362.10" *)
module RegRst_0x9f365fdf6c8998a(clk, in_, out, reset);
  (* src = "gcd.v:331.24-331.27" *)
  input [0:0] clk;
  wire [0:0] clk;
  (* src = "gcd.v:332.24-332.27" *)
  input [1:0] in_;
  wire [1:0] in_;
  (* src = "gcd.v:333.24-333.27" *)
  output [1:0] out;
  reg [1:0] out;
  (* src = "gcd.v:334.24-334.29" *)
  input [0:0] reset;
  wire [0:0] reset;
  wire _0_;
  wire _1_;
  wire [1:0] _2_;
  (* src = "gcd.v:352.3-359.6" *)
  always @(posedge clk)
    out <= _2_;
  assign _2_ = reset ? { _1_, _0_ } : in_;
  gf180mcu_fd_sc_mcu7t5v0__tiel_1 _5_ (
    .Y(_0_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel_1 _6_ (
    .Y(_1_)
  );
endmodule

(* src = "gcd.v:733.1-756.10" *)
module Subtractor_0x422b1f52edd46a85(clk, in0, in1, out, reset);
  (* src = "gcd.v:735.24-735.27" *)
  input [0:0] clk;
  wire [0:0] clk;
  (* src = "gcd.v:736.24-736.27" *)
  input [15:0] in0;
  wire [15:0] in0;
  (* src = "gcd.v:737.24-737.27" *)
  input [15:0] in1;
  wire [15:0] in1;
  (* src = "gcd.v:738.24-738.27" *)
  output [15:0] out;
  wire [15:0] out;
  (* src = "gcd.v:739.24-739.29" *)
  input [0:0] reset;
  wire [0:0] reset;
  assign out = in0 - (* src = "gcd.v:752.12-752.19" *) in1;
endmodule

(* src = "gcd.v:619.1-641.10" *)
module ZeroComparator_0x422b1f52edd46a85(clk, in_, out, reset);
  (* src = "gcd.v:621.24-621.27" *)
  input [0:0] clk;
  wire [0:0] clk;
  (* src = "gcd.v:622.24-622.27" *)
  input [15:0] in_;
  wire [15:0] in_;
  (* src = "gcd.v:623.24-623.27" *)
  output [0:0] out;
  wire [0:0] out;
  (* src = "gcd.v:624.24-624.29" *)
  input [0:0] reset;
  wire [0:0] reset;
  assign out = ! (* src = "gcd.v:637.12-637.20" *) in_;
endmodule

(* top =  1  *)
(* src = "gcd.v:11.1-102.10" *)
module gcd(clk, req_msg, req_rdy, req_val, reset, resp_msg, resp_rdy, resp_val);
  (* src = "gcd.v:13.15-13.18" *)
  input clk;
  wire clk;
  (* src = "gcd.v:14.24-14.31" *)
  input [31:0] req_msg;
  wire [31:0] req_msg;
  (* src = "gcd.v:15.15-15.22" *)
  output req_rdy;
  wire req_rdy;
  (* src = "gcd.v:16.15-16.22" *)
  input req_val;
  wire req_val;
  (* src = "gcd.v:17.15-17.20" *)
  input reset;
  wire reset;
  (* src = "gcd.v:18.24-18.32" *)
  output [15:0] resp_msg;
  wire [15:0] resp_msg;
  (* src = "gcd.v:19.15-19.23" *)
  input resp_rdy;
  wire resp_rdy;
  (* src = "gcd.v:20.15-20.23" *)
  output resp_val;
  wire resp_val;
  (* src = "gcd.v:30.19-30.33" *)
  wire [1:0] \ctrl$a_mux_sel ;
  (* src = "gcd.v:34.19-34.32" *)
  wire [0:0] \ctrl$a_reg_en ;
  (* src = "gcd.v:32.19-32.33" *)
  wire [0:0] \ctrl$b_mux_sel ;
  (* src = "gcd.v:33.19-33.32" *)
  wire [0:0] \ctrl$b_reg_en ;
  (* src = "gcd.v:26.19-26.27" *)
  wire [0:0] \ctrl$clk ;
  (* src = "gcd.v:27.19-27.33" *)
  wire [0:0] \ctrl$is_a_lt_b ;
  (* src = "gcd.v:24.19-24.33" *)
  wire [0:0] \ctrl$is_b_zero ;
  (* src = "gcd.v:35.19-35.31" *)
  wire [0:0] \ctrl$req_rdy ;
  (* src = "gcd.v:28.19-28.31" *)
  wire [0:0] \ctrl$req_val ;
  (* src = "gcd.v:29.19-29.29" *)
  wire [0:0] \ctrl$reset ;
  (* src = "gcd.v:25.19-25.32" *)
  wire [0:0] \ctrl$resp_rdy ;
  (* src = "gcd.v:31.19-31.32" *)
  wire [0:0] \ctrl$resp_val ;
  (* src = "gcd.v:54.19-54.34" *)
  wire [1:0] \dpath$a_mux_sel ;
  (* src = "gcd.v:61.19-61.33" *)
  wire [0:0] \dpath$a_reg_en ;
  (* src = "gcd.v:58.19-58.34" *)
  wire [0:0] \dpath$b_mux_sel ;
  (* src = "gcd.v:60.19-60.33" *)
  wire [0:0] \dpath$b_reg_en ;
  (* src = "gcd.v:55.19-55.28" *)
  wire [0:0] \dpath$clk ;
  (* src = "gcd.v:64.19-64.34" *)
  wire [0:0] \dpath$is_a_lt_b ;
  (* src = "gcd.v:62.19-62.34" *)
  wire [0:0] \dpath$is_b_zero ;
  (* src = "gcd.v:57.19-57.34" *)
  wire [15:0] \dpath$req_msg_a ;
  (* src = "gcd.v:56.19-56.34" *)
  wire [15:0] \dpath$req_msg_b ;
  (* src = "gcd.v:59.19-59.30" *)
  wire [0:0] \dpath$reset ;
  (* src = "gcd.v:63.19-63.33" *)
  wire [15:0] \dpath$resp_msg ;
  (* module_not_derived = 32'd1 *)
  (* src = "gcd.v:37.37-51.4" *)
  GcdUnitCtrlRTL_0x4d0fc71ead8d3d9e ctrl (
    .a_mux_sel(\ctrl$a_mux_sel ),
    .a_reg_en(\ctrl$a_reg_en ),
    .b_mux_sel(\ctrl$b_mux_sel ),
    .b_reg_en(\ctrl$b_reg_en ),
    .clk(clk),
    .is_a_lt_b(\ctrl$is_a_lt_b ),
    .is_b_zero(\ctrl$is_b_zero ),
    .req_rdy(\ctrl$req_rdy ),
    .req_val(req_val),
    .reset(reset),
    .resp_rdy(resp_rdy),
    .resp_val(\ctrl$resp_val )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "gcd.v:66.38-79.4" *)
  GcdUnitDpathRTL_0x4d0fc71ead8d3d9e dpath (
    .a_mux_sel(\ctrl$a_mux_sel ),
    .a_reg_en(\ctrl$a_reg_en ),
    .b_mux_sel(\ctrl$b_mux_sel ),
    .b_reg_en(\ctrl$b_reg_en ),
    .clk(clk),
    .is_a_lt_b(\ctrl$is_a_lt_b ),
    .is_b_zero(\ctrl$is_b_zero ),
    .req_msg_a(req_msg[31:16]),
    .req_msg_b(req_msg[15:0]),
    .reset(reset),
    .resp_msg(\dpath$resp_msg )
  );
  assign \ctrl$clk  = clk;
  assign \ctrl$req_val  = req_val;
  assign \ctrl$reset  = reset;
  assign \ctrl$resp_rdy  = resp_rdy;
  assign \dpath$a_mux_sel  = \ctrl$a_mux_sel ;
  assign \dpath$a_reg_en  = \ctrl$a_reg_en ;
  assign \dpath$b_mux_sel  = \ctrl$b_mux_sel ;
  assign \dpath$b_reg_en  = \ctrl$b_reg_en ;
  assign \dpath$clk  = clk;
  assign \dpath$is_a_lt_b  = \ctrl$is_a_lt_b ;
  assign \dpath$is_b_zero  = \ctrl$is_b_zero ;
  assign \dpath$req_msg_a  = req_msg[31:16];
  assign \dpath$req_msg_b  = req_msg[15:0];
  assign \dpath$reset  = reset;
  assign req_rdy = \ctrl$req_rdy ;
  assign resp_msg = \dpath$resp_msg ;
  assign resp_val = \ctrl$resp_val ;
endmodule
